name: ter_ensino_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+4
  cupertino_icons: ^0.1.3
  scoped_model: ^1.0.1
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/img_default_profile.jpg